### ISSUE TITLE
Wallabag support as external service

### ISSUE THREAD

**Issue by foxmask** [feedhq/feedhq#105]
It could be fine to integrate [Wallabag](https://www.wallabag.org/) as a new external service. 

In case You'll be interested I made the [API](https://github.com/foxmask/wallabag_api)

**Comment by brutasse** [comment]
Yes, it'd be interesting. I'll look into it.

**Comment by foxmask** [comment]
notice to avoid a trap :) : as wallabag is a selfhosted service, the TTL of the token is very very short compared to "pocket" or other internet service. On my side with another project, I renew the token sometimes automatically (and not on demand when the user token has expired). But it's not a big deal as wallabag is hosted on the same server of our own service (feedhq or other)'s not a big deal as wallabag is hosted on the same server of our own service (feedhq or other)

**Comment by nicosomb** [comment]
https://github.com/feedhq/feedhq/issues/70 :)

**Comment by foxmask** [comment]
2years ago. too long to remember :) so this could be close. sorry for the "noise"

**Comment by brutasse** [comment]
haha :) Is the current implementation still valid? Much easier to integrate from a web app than with an OAuth API

**Comment by nicosomb** [comment]
It's still valid for wallabag 1.x. 
About 2.x, you need OAuth.

**Comment by brutasse** [comment]
Hm. Let's leave this issue open then.

**Comment by nicosomb** [comment]
Our API documentation is here: http://doc.wallabag.org/en/master/developer/api.html

**Comment by loicm** [comment]
I don't know if I can be of any help on this but I'd like this feature to be implemented :)
