### ISSUE TITLE
Installation process : missing details 

### ISSUE THREAD

**Issue by foxmask** [feedhq/feedhq#106]
During the installation process I met 2 problems 

after 

```
source env/bin/activate
```

the process says : 

```
add2virtualenv .
```

but 

```
bash: add2virtualenv : command not found
```

and later 

```
./manage.py test
    from django_webtest import WebTest as BaseWebTest
ImportError: No module named django_webtest
```

and later  in the part  `The arguments are queue names.`

> Once your application is deployed ... you can add users to the application. 

But in fact we cant, as we didnt create a superuser before, did we ?

**Comment by brutasse** [comment]
Thanks. `add2virtualenv` is from `virtualenvwrapper`, not virtualenv itself. I should update the instructions to read `python setup.py develop` which is more standard.

For django-webtest you need to install from `requirements-dev.txt`.

I think the old `syncdb` command used to prompt to create a superuser, it might not be the case anymore with `migrate`.
