### ISSUE TITLE
PubSubHubbub support?

### ISSUE THREAD

**Issue by julien51** [feedhq/feedhq#93]
Hello @brutasse !
I hope you're well.

I was looking at the UA who poll Superfeedr's blog feed, i found FeedHQ... I then checked if you were subscribed to our feed via PubSubHubbub and found that you were not :( This is sad.

It'd be amazing if you added PubSubHubbub support. I wrote [a tutorial](http://blog.superfeedr.com/howto-pubsubhubbub/) for this. 

Let me know if I can help.

**Comment by julien51** [comment]
Wooops! I was looking at the wrong URL in our database... you are indeed subscribed to the feed :)

**Comment by brutasse** [comment]
Haha yes, thanks for checking! That's a nice tutorial, btw :)
